# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committiehead', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(related_name='committiemember', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
