# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atfaluna', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('children', models.ManyToManyField(blank=True, related_name='child', to='atfaluna.Children')),
                ('father', models.ManyToManyField(blank=True, related_name='fathers', to='atfaluna.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1500)),
                ('committies', models.ManyToManyField(related_name='core', to='authentication.Committie')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head', models.BooleanField(default=False)),
                ('is_UB', models.BooleanField(default=False)),
                ('faculty', models.CharField(choices=[('Pharmacy', 'Pharmacy'), ('Management', 'Management'), ('Engineering', 'Engineering'), ('Applied Arts', 'Applied Arts'), ('Business Informatics', 'Business Informatics')], default='Pharmacy', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('guc_id', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('new_messages', models.IntegerField(default=0)),
                ('position', models.CharField(choices=[('President', 'President'), ('Core President', 'Core President'), ('Support President', 'Support President'), ('Head', 'Head'), ('Member', 'Member')], default='Member', max_length=100)),
                ('committie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committie', to='authentication.Committie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=3000)),
                ('is_read', models.BooleanField(default=False)),
                ('reciver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='authentication.Member')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifier', to='authentication.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1500)),
                ('committies', models.ManyToManyField(related_name='support', to='authentication.Committie')),
                ('support_president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supprt_president', to='authentication.Member')),
            ],
        ),
        migrations.AddField(
            model_name='core',
            name='core_president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_president', to='authentication.Member'),
        ),
        migrations.AddField(
            model_name='committie',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committiehead', to='authentication.Member'),
        ),
        migrations.AddField(
            model_name='committie',
            name='home',
            field=models.ManyToManyField(blank=True, related_name='house', to='atfaluna.Home'),
        ),
        migrations.AddField(
            model_name='committie',
            name='mother',
            field=models.ManyToManyField(blank=True, related_name='mothers', to='atfaluna.Parent'),
        ),
    ]
