# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head', models.BooleanField(default=False)),
                ('is_UB', models.BooleanField(default=False)),
                ('faculty', models.CharField(choices=[('Pharmacy', 'Pharmacy'), ('Management', 'Management'), ('Engineering', 'Engineering'), ('Applied Arts', 'Applied Arts'), ('Business Informatics', 'Business Informatics')], default='Pharmacy', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('guc_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=3000)),
                ('is_read', models.BooleanField(default=False)),
                ('new_messages', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='committie',
            name='member',
        ),
        migrations.AlterField(
            model_name='committie',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committiehead', to='authentication.Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='notification',
            field=models.ManyToManyField(default='no new notifications', to='authentication.Notification'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
