# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160506_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='committie',
            field=models.ManyToManyField(related_name='committie', to='authentication.Committie'),
        ),
    ]
