# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atfaluna', '0002_family_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='ommi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
