# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atfaluna', '0003_auto_20160519_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='relif_needed',
        ),
        migrations.AddField(
            model_name='home',
            name='relif_needed',
            field=models.CharField(choices=[('True', 'نعم'), ('False', 'لا')], default='False', max_length=100),
        ),
    ]
